uniform vec4 u_palette[256];

vec4 effect(vec4 _color, Image texture, vec2 texture_coords, vec2 screen_coords)
{
    // completely ignore the color field because we don't want to tint the canvas in any way.

    vec4 texture_color = Texel(texture, texture_coords);
    int index = int(texture_color.r * 255.0 + 0.5);

    // Lookup the color from the palette by index.
    // Using deterministic arrays to support old mobile phones.
    vec4 col = vec4(1.0);

    // I couldn't find a less stupid solution for this.

    if      (index ==   0) col = u_palette[  0];
    else if (index ==   1) col = u_palette[  1];
    else if (index ==   2) col = u_palette[  2];
    else if (index ==   3) col = u_palette[  3];
    else if (index ==   4) col = u_palette[  4];
    else if (index ==   5) col = u_palette[  5];
    else if (index ==   6) col = u_palette[  6];
    else if (index ==   7) col = u_palette[  7];
    else if (index ==   8) col = u_palette[  8];
    else if (index ==   9) col = u_palette[  9];
    else if (index ==  10) col = u_palette[ 10];
    else if (index ==  11) col = u_palette[ 11];
    else if (index ==  12) col = u_palette[ 12];
    else if (index ==  13) col = u_palette[ 13];
    else if (index ==  14) col = u_palette[ 14];
    else if (index ==  15) col = u_palette[ 15];
    else if (index ==  16) col = u_palette[ 16];
    else if (index ==  17) col = u_palette[ 17];
    else if (index ==  18) col = u_palette[ 18];
    else if (index ==  19) col = u_palette[ 19];
    else if (index ==  20) col = u_palette[ 20];
    else if (index ==  21) col = u_palette[ 21];
    else if (index ==  22) col = u_palette[ 22];
    else if (index ==  23) col = u_palette[ 23];
    else if (index ==  24) col = u_palette[ 24];
    else if (index ==  25) col = u_palette[ 25];
    else if (index ==  26) col = u_palette[ 26];
    else if (index ==  27) col = u_palette[ 27];
    else if (index ==  28) col = u_palette[ 28];
    else if (index ==  29) col = u_palette[ 29];
    else if (index ==  30) col = u_palette[ 30];
    else if (index ==  31) col = u_palette[ 31];
    else if (index ==  32) col = u_palette[ 32];
    else if (index ==  33) col = u_palette[ 33];
    else if (index ==  34) col = u_palette[ 34];
    else if (index ==  35) col = u_palette[ 35];
    else if (index ==  36) col = u_palette[ 36];
    else if (index ==  37) col = u_palette[ 37];
    else if (index ==  38) col = u_palette[ 38];
    else if (index ==  39) col = u_palette[ 39];
    else if (index ==  40) col = u_palette[ 40];
    else if (index ==  41) col = u_palette[ 41];
    else if (index ==  42) col = u_palette[ 42];
    else if (index ==  43) col = u_palette[ 43];
    else if (index ==  44) col = u_palette[ 44];
    else if (index ==  45) col = u_palette[ 45];
    else if (index ==  46) col = u_palette[ 46];
    else if (index ==  47) col = u_palette[ 47];
    else if (index ==  48) col = u_palette[ 48];
    else if (index ==  49) col = u_palette[ 49];
    else if (index ==  50) col = u_palette[ 50];
    else if (index ==  51) col = u_palette[ 51];
    else if (index ==  52) col = u_palette[ 52];
    else if (index ==  53) col = u_palette[ 53];
    else if (index ==  54) col = u_palette[ 54];
    else if (index ==  55) col = u_palette[ 55];
    else if (index ==  56) col = u_palette[ 56];
    else if (index ==  57) col = u_palette[ 57];
    else if (index ==  58) col = u_palette[ 58];
    else if (index ==  59) col = u_palette[ 59];
    else if (index ==  60) col = u_palette[ 60];
    else if (index ==  61) col = u_palette[ 61];
    else if (index ==  62) col = u_palette[ 62];
    else if (index ==  63) col = u_palette[ 63];
    else if (index ==  64) col = u_palette[ 64];
    else if (index ==  65) col = u_palette[ 65];
    else if (index ==  66) col = u_palette[ 66];
    else if (index ==  67) col = u_palette[ 67];
    else if (index ==  68) col = u_palette[ 68];
    else if (index ==  69) col = u_palette[ 69];
    else if (index ==  70) col = u_palette[ 70];
    else if (index ==  71) col = u_palette[ 71];
    else if (index ==  72) col = u_palette[ 72];
    else if (index ==  73) col = u_palette[ 73];
    else if (index ==  74) col = u_palette[ 74];
    else if (index ==  75) col = u_palette[ 75];
    else if (index ==  76) col = u_palette[ 76];
    else if (index ==  77) col = u_palette[ 77];
    else if (index ==  78) col = u_palette[ 78];
    else if (index ==  79) col = u_palette[ 79];
    else if (index ==  80) col = u_palette[ 80];
    else if (index ==  81) col = u_palette[ 81];
    else if (index ==  82) col = u_palette[ 82];
    else if (index ==  83) col = u_palette[ 83];
    else if (index ==  84) col = u_palette[ 84];
    else if (index ==  85) col = u_palette[ 85];
    else if (index ==  86) col = u_palette[ 86];
    else if (index ==  87) col = u_palette[ 87];
    else if (index ==  88) col = u_palette[ 88];
    else if (index ==  89) col = u_palette[ 89];
    else if (index ==  90) col = u_palette[ 90];
    else if (index ==  91) col = u_palette[ 91];
    else if (index ==  92) col = u_palette[ 92];
    else if (index ==  93) col = u_palette[ 93];
    else if (index ==  94) col = u_palette[ 94];
    else if (index ==  95) col = u_palette[ 95];
    else if (index ==  96) col = u_palette[ 96];
    else if (index ==  97) col = u_palette[ 97];
    else if (index ==  98) col = u_palette[ 98];
    else if (index ==  99) col = u_palette[ 99];
    else if (index == 100) col = u_palette[100];
    else if (index == 101) col = u_palette[101];
    else if (index == 102) col = u_palette[102];
    else if (index == 103) col = u_palette[103];
    else if (index == 104) col = u_palette[104];
    else if (index == 105) col = u_palette[105];
    else if (index == 106) col = u_palette[106];
    else if (index == 107) col = u_palette[107];
    else if (index == 108) col = u_palette[108];
    else if (index == 109) col = u_palette[109];
    else if (index == 110) col = u_palette[110];
    else if (index == 111) col = u_palette[111];
    else if (index == 112) col = u_palette[112];
    else if (index == 113) col = u_palette[113];
    else if (index == 114) col = u_palette[114];
    else if (index == 115) col = u_palette[115];
    else if (index == 116) col = u_palette[116];
    else if (index == 117) col = u_palette[117];
    else if (index == 118) col = u_palette[118];
    else if (index == 119) col = u_palette[119];
    else if (index == 120) col = u_palette[120];
    else if (index == 121) col = u_palette[121];
    else if (index == 122) col = u_palette[122];
    else if (index == 123) col = u_palette[123];
    else if (index == 124) col = u_palette[124];
    else if (index == 125) col = u_palette[125];
    else if (index == 126) col = u_palette[126];
    else if (index == 127) col = u_palette[127];
    else if (index == 128) col = u_palette[128];
    else if (index == 129) col = u_palette[129];
    else if (index == 130) col = u_palette[130];
    else if (index == 131) col = u_palette[131];
    else if (index == 132) col = u_palette[132];
    else if (index == 133) col = u_palette[133];
    else if (index == 134) col = u_palette[134];
    else if (index == 135) col = u_palette[135];
    else if (index == 136) col = u_palette[136];
    else if (index == 137) col = u_palette[137];
    else if (index == 138) col = u_palette[138];
    else if (index == 139) col = u_palette[139];
    else if (index == 140) col = u_palette[140];
    else if (index == 141) col = u_palette[141];
    else if (index == 142) col = u_palette[142];
    else if (index == 143) col = u_palette[143];
    else if (index == 144) col = u_palette[144];
    else if (index == 145) col = u_palette[145];
    else if (index == 146) col = u_palette[146];
    else if (index == 147) col = u_palette[147];
    else if (index == 148) col = u_palette[148];
    else if (index == 149) col = u_palette[149];
    else if (index == 150) col = u_palette[150];
    else if (index == 151) col = u_palette[151];
    else if (index == 152) col = u_palette[152];
    else if (index == 153) col = u_palette[153];
    else if (index == 154) col = u_palette[154];
    else if (index == 155) col = u_palette[155];
    else if (index == 156) col = u_palette[156];
    else if (index == 157) col = u_palette[157];
    else if (index == 158) col = u_palette[158];
    else if (index == 159) col = u_palette[159];
    else if (index == 160) col = u_palette[160];
    else if (index == 161) col = u_palette[161];
    else if (index == 162) col = u_palette[162];
    else if (index == 163) col = u_palette[163];
    else if (index == 164) col = u_palette[164];
    else if (index == 165) col = u_palette[165];
    else if (index == 166) col = u_palette[166];
    else if (index == 167) col = u_palette[167];
    else if (index == 168) col = u_palette[168];
    else if (index == 169) col = u_palette[169];
    else if (index == 170) col = u_palette[170];
    else if (index == 171) col = u_palette[171];
    else if (index == 172) col = u_palette[172];
    else if (index == 173) col = u_palette[173];
    else if (index == 174) col = u_palette[174];
    else if (index == 175) col = u_palette[175];
    else if (index == 176) col = u_palette[176];
    else if (index == 177) col = u_palette[177];
    else if (index == 178) col = u_palette[178];
    else if (index == 179) col = u_palette[179];
    else if (index == 180) col = u_palette[180];
    else if (index == 181) col = u_palette[181];
    else if (index == 182) col = u_palette[182];
    else if (index == 183) col = u_palette[183];
    else if (index == 184) col = u_palette[184];
    else if (index == 185) col = u_palette[185];
    else if (index == 186) col = u_palette[186];
    else if (index == 187) col = u_palette[187];
    else if (index == 188) col = u_palette[188];
    else if (index == 189) col = u_palette[189];
    else if (index == 190) col = u_palette[190];
    else if (index == 191) col = u_palette[191];
    else if (index == 192) col = u_palette[192];
    else if (index == 193) col = u_palette[193];
    else if (index == 194) col = u_palette[194];
    else if (index == 195) col = u_palette[195];
    else if (index == 196) col = u_palette[196];
    else if (index == 197) col = u_palette[197];
    else if (index == 198) col = u_palette[198];
    else if (index == 199) col = u_palette[199];
    else if (index == 200) col = u_palette[200];
    else if (index == 201) col = u_palette[201];
    else if (index == 202) col = u_palette[202];
    else if (index == 203) col = u_palette[203];
    else if (index == 204) col = u_palette[204];
    else if (index == 205) col = u_palette[205];
    else if (index == 206) col = u_palette[206];
    else if (index == 207) col = u_palette[207];
    else if (index == 208) col = u_palette[208];
    else if (index == 209) col = u_palette[209];
    else if (index == 210) col = u_palette[210];
    else if (index == 211) col = u_palette[211];
    else if (index == 212) col = u_palette[212];
    else if (index == 213) col = u_palette[213];
    else if (index == 214) col = u_palette[214];
    else if (index == 215) col = u_palette[215];
    else if (index == 216) col = u_palette[216];
    else if (index == 217) col = u_palette[217];
    else if (index == 218) col = u_palette[218];
    else if (index == 219) col = u_palette[219];
    else if (index == 220) col = u_palette[220];
    else if (index == 221) col = u_palette[221];
    else if (index == 222) col = u_palette[222];
    else if (index == 223) col = u_palette[223];
    else if (index == 224) col = u_palette[224];
    else if (index == 247) col = u_palette[247];
    else if (index == 248) col = u_palette[248];
    else if (index == 249) col = u_palette[249];
    else if (index == 250) col = u_palette[250];
    else if (index == 251) col = u_palette[251];
    else if (index == 252) col = u_palette[252];
    else if (index == 253) col = u_palette[253];
    else if (index == 254) col = u_palette[254];
    else if (index == 255) col = u_palette[255];
    
    // Display grayscale levels for debugging.
    // col = vec4(float(index) / 255.0);
    // col.a = 1.0;

    return col;
}