uniform int u_transparent[256]; // array of 0 or 1;
uniform int u_remap[256]; // array of integer values in range [0, 255];

vec4 effect(vec4 color, Image texture, vec2 texture_coords, vec2 screen_coords)
{
    // Any shapes/geometry drawing operation would have a texture of a single white pixel (#FFFFFFFF).
    // Any image would have it's blue channel set to 0.0.

    vec4 texture_color = Texel(texture, texture_coords);

    int index = int(color.r * 255.0 + 0.5);

    // Discard transparent pixels for images only.
    if (texture_color.b == 0.0) {
        index = int(texture_color.r * 255.0 + 0.5);

        if (u_transparent[index] == 1) {
            discard;
        }
    }

    // Remap the color.
    
    // I couldn't find a less stupid solution for this.

    if      (index ==   0) index = u_remap[  0];
    else if (index ==   1) index = u_remap[  1];
    else if (index ==   2) index = u_remap[  2];
    else if (index ==   3) index = u_remap[  3];
    else if (index ==   4) index = u_remap[  4];
    else if (index ==   5) index = u_remap[  5];
    else if (index ==   6) index = u_remap[  6];
    else if (index ==   7) index = u_remap[  7];
    else if (index ==   8) index = u_remap[  8];
    else if (index ==   9) index = u_remap[  9];
    else if (index ==  10) index = u_remap[ 10];
    else if (index ==  11) index = u_remap[ 11];
    else if (index ==  12) index = u_remap[ 12];
    else if (index ==  13) index = u_remap[ 13];
    else if (index ==  14) index = u_remap[ 14];
    else if (index ==  15) index = u_remap[ 15];
    else if (index ==  16) index = u_remap[ 16];
    else if (index ==  17) index = u_remap[ 17];
    else if (index ==  18) index = u_remap[ 18];
    else if (index ==  19) index = u_remap[ 19];
    else if (index ==  20) index = u_remap[ 20];
    else if (index ==  21) index = u_remap[ 21];
    else if (index ==  22) index = u_remap[ 22];
    else if (index ==  23) index = u_remap[ 23];
    else if (index ==  24) index = u_remap[ 24];
    else if (index ==  25) index = u_remap[ 25];
    else if (index ==  26) index = u_remap[ 26];
    else if (index ==  27) index = u_remap[ 27];
    else if (index ==  28) index = u_remap[ 28];
    else if (index ==  29) index = u_remap[ 29];
    else if (index ==  30) index = u_remap[ 30];
    else if (index ==  31) index = u_remap[ 31];
    else if (index ==  32) index = u_remap[ 32];
    else if (index ==  33) index = u_remap[ 33];
    else if (index ==  34) index = u_remap[ 34];
    else if (index ==  35) index = u_remap[ 35];
    else if (index ==  36) index = u_remap[ 36];
    else if (index ==  37) index = u_remap[ 37];
    else if (index ==  38) index = u_remap[ 38];
    else if (index ==  39) index = u_remap[ 39];
    else if (index ==  40) index = u_remap[ 40];
    else if (index ==  41) index = u_remap[ 41];
    else if (index ==  42) index = u_remap[ 42];
    else if (index ==  43) index = u_remap[ 43];
    else if (index ==  44) index = u_remap[ 44];
    else if (index ==  45) index = u_remap[ 45];
    else if (index ==  46) index = u_remap[ 46];
    else if (index ==  47) index = u_remap[ 47];
    else if (index ==  48) index = u_remap[ 48];
    else if (index ==  49) index = u_remap[ 49];
    else if (index ==  50) index = u_remap[ 50];
    else if (index ==  51) index = u_remap[ 51];
    else if (index ==  52) index = u_remap[ 52];
    else if (index ==  53) index = u_remap[ 53];
    else if (index ==  54) index = u_remap[ 54];
    else if (index ==  55) index = u_remap[ 55];
    else if (index ==  56) index = u_remap[ 56];
    else if (index ==  57) index = u_remap[ 57];
    else if (index ==  58) index = u_remap[ 58];
    else if (index ==  59) index = u_remap[ 59];
    else if (index ==  60) index = u_remap[ 60];
    else if (index ==  61) index = u_remap[ 61];
    else if (index ==  62) index = u_remap[ 62];
    else if (index ==  63) index = u_remap[ 63];
    else if (index ==  64) index = u_remap[ 64];
    else if (index ==  65) index = u_remap[ 65];
    else if (index ==  66) index = u_remap[ 66];
    else if (index ==  67) index = u_remap[ 67];
    else if (index ==  68) index = u_remap[ 68];
    else if (index ==  69) index = u_remap[ 69];
    else if (index ==  70) index = u_remap[ 70];
    else if (index ==  71) index = u_remap[ 71];
    else if (index ==  72) index = u_remap[ 72];
    else if (index ==  73) index = u_remap[ 73];
    else if (index ==  74) index = u_remap[ 74];
    else if (index ==  75) index = u_remap[ 75];
    else if (index ==  76) index = u_remap[ 76];
    else if (index ==  77) index = u_remap[ 77];
    else if (index ==  78) index = u_remap[ 78];
    else if (index ==  79) index = u_remap[ 79];
    else if (index ==  80) index = u_remap[ 80];
    else if (index ==  81) index = u_remap[ 81];
    else if (index ==  82) index = u_remap[ 82];
    else if (index ==  83) index = u_remap[ 83];
    else if (index ==  84) index = u_remap[ 84];
    else if (index ==  85) index = u_remap[ 85];
    else if (index ==  86) index = u_remap[ 86];
    else if (index ==  87) index = u_remap[ 87];
    else if (index ==  88) index = u_remap[ 88];
    else if (index ==  89) index = u_remap[ 89];
    else if (index ==  90) index = u_remap[ 90];
    else if (index ==  91) index = u_remap[ 91];
    else if (index ==  92) index = u_remap[ 92];
    else if (index ==  93) index = u_remap[ 93];
    else if (index ==  94) index = u_remap[ 94];
    else if (index ==  95) index = u_remap[ 95];
    else if (index ==  96) index = u_remap[ 96];
    else if (index ==  97) index = u_remap[ 97];
    else if (index ==  98) index = u_remap[ 98];
    else if (index ==  99) index = u_remap[ 99];
    else if (index == 100) index = u_remap[100];
    else if (index == 101) index = u_remap[101];
    else if (index == 102) index = u_remap[102];
    else if (index == 103) index = u_remap[103];
    else if (index == 104) index = u_remap[104];
    else if (index == 105) index = u_remap[105];
    else if (index == 106) index = u_remap[106];
    else if (index == 107) index = u_remap[107];
    else if (index == 108) index = u_remap[108];
    else if (index == 109) index = u_remap[109];
    else if (index == 110) index = u_remap[110];
    else if (index == 111) index = u_remap[111];
    else if (index == 112) index = u_remap[112];
    else if (index == 113) index = u_remap[113];
    else if (index == 114) index = u_remap[114];
    else if (index == 115) index = u_remap[115];
    else if (index == 116) index = u_remap[116];
    else if (index == 117) index = u_remap[117];
    else if (index == 118) index = u_remap[118];
    else if (index == 119) index = u_remap[119];
    else if (index == 120) index = u_remap[120];
    else if (index == 121) index = u_remap[121];
    else if (index == 122) index = u_remap[122];
    else if (index == 123) index = u_remap[123];
    else if (index == 124) index = u_remap[124];
    else if (index == 125) index = u_remap[125];
    else if (index == 126) index = u_remap[126];
    else if (index == 127) index = u_remap[127];
    else if (index == 128) index = u_remap[128];
    else if (index == 129) index = u_remap[129];
    else if (index == 130) index = u_remap[130];
    else if (index == 131) index = u_remap[131];
    else if (index == 132) index = u_remap[132];
    else if (index == 133) index = u_remap[133];
    else if (index == 134) index = u_remap[134];
    else if (index == 135) index = u_remap[135];
    else if (index == 136) index = u_remap[136];
    else if (index == 137) index = u_remap[137];
    else if (index == 138) index = u_remap[138];
    else if (index == 139) index = u_remap[139];
    else if (index == 140) index = u_remap[140];
    else if (index == 141) index = u_remap[141];
    else if (index == 142) index = u_remap[142];
    else if (index == 143) index = u_remap[143];
    else if (index == 144) index = u_remap[144];
    else if (index == 145) index = u_remap[145];
    else if (index == 146) index = u_remap[146];
    else if (index == 147) index = u_remap[147];
    else if (index == 148) index = u_remap[148];
    else if (index == 149) index = u_remap[149];
    else if (index == 150) index = u_remap[150];
    else if (index == 151) index = u_remap[151];
    else if (index == 152) index = u_remap[152];
    else if (index == 153) index = u_remap[153];
    else if (index == 154) index = u_remap[154];
    else if (index == 155) index = u_remap[155];
    else if (index == 156) index = u_remap[156];
    else if (index == 157) index = u_remap[157];
    else if (index == 158) index = u_remap[158];
    else if (index == 159) index = u_remap[159];
    else if (index == 160) index = u_remap[160];
    else if (index == 161) index = u_remap[161];
    else if (index == 162) index = u_remap[162];
    else if (index == 163) index = u_remap[163];
    else if (index == 164) index = u_remap[164];
    else if (index == 165) index = u_remap[165];
    else if (index == 166) index = u_remap[166];
    else if (index == 167) index = u_remap[167];
    else if (index == 168) index = u_remap[168];
    else if (index == 169) index = u_remap[169];
    else if (index == 170) index = u_remap[170];
    else if (index == 171) index = u_remap[171];
    else if (index == 172) index = u_remap[172];
    else if (index == 173) index = u_remap[173];
    else if (index == 174) index = u_remap[174];
    else if (index == 175) index = u_remap[175];
    else if (index == 176) index = u_remap[176];
    else if (index == 177) index = u_remap[177];
    else if (index == 178) index = u_remap[178];
    else if (index == 179) index = u_remap[179];
    else if (index == 180) index = u_remap[180];
    else if (index == 181) index = u_remap[181];
    else if (index == 182) index = u_remap[182];
    else if (index == 183) index = u_remap[183];
    else if (index == 184) index = u_remap[184];
    else if (index == 185) index = u_remap[185];
    else if (index == 186) index = u_remap[186];
    else if (index == 187) index = u_remap[187];
    else if (index == 188) index = u_remap[188];
    else if (index == 189) index = u_remap[189];
    else if (index == 190) index = u_remap[190];
    else if (index == 191) index = u_remap[191];
    else if (index == 192) index = u_remap[192];
    else if (index == 193) index = u_remap[193];
    else if (index == 194) index = u_remap[194];
    else if (index == 195) index = u_remap[195];
    else if (index == 196) index = u_remap[196];
    else if (index == 197) index = u_remap[197];
    else if (index == 198) index = u_remap[198];
    else if (index == 199) index = u_remap[199];
    else if (index == 200) index = u_remap[200];
    else if (index == 201) index = u_remap[201];
    else if (index == 202) index = u_remap[202];
    else if (index == 203) index = u_remap[203];
    else if (index == 204) index = u_remap[204];
    else if (index == 205) index = u_remap[205];
    else if (index == 206) index = u_remap[206];
    else if (index == 207) index = u_remap[207];
    else if (index == 208) index = u_remap[208];
    else if (index == 209) index = u_remap[209];
    else if (index == 210) index = u_remap[210];
    else if (index == 211) index = u_remap[211];
    else if (index == 212) index = u_remap[212];
    else if (index == 213) index = u_remap[213];
    else if (index == 214) index = u_remap[214];
    else if (index == 215) index = u_remap[215];
    else if (index == 216) index = u_remap[216];
    else if (index == 217) index = u_remap[217];
    else if (index == 218) index = u_remap[218];
    else if (index == 219) index = u_remap[219];
    else if (index == 220) index = u_remap[220];
    else if (index == 221) index = u_remap[221];
    else if (index == 222) index = u_remap[222];
    else if (index == 223) index = u_remap[223];
    else if (index == 224) index = u_remap[224];
    else if (index == 247) index = u_remap[247];
    else if (index == 248) index = u_remap[248];
    else if (index == 249) index = u_remap[249];
    else if (index == 250) index = u_remap[250];
    else if (index == 251) index = u_remap[251];
    else if (index == 252) index = u_remap[252];
    else if (index == 253) index = u_remap[253];
    else if (index == 254) index = u_remap[254];
    else if (index == 255) index = u_remap[255];

    return vec4(float(index) / 255.0, 1.0, 1.0, 1.0);
}