color(12) print("Terminal Programs                     ") sleep(0.001)
color(07) print("REBOOT   SHUTDOWN   APIS   PERIPHERALS") sleep(0.001)
color(07) print("LOAD <FileName>    SAVE <FileName>    ") sleep(0.001)
color(07) print("RUN                NEW             CLS") sleep(0.001)
color(07) print("IMPORT <SheetFile> EXPORT <Sheet>.png ") sleep(0.001)
color(07) print("INSTALL_DEMOS      DIR / LS           ") sleep(0.001)
color(07) print("MKDIR <DirName>    RM <file/directory>") sleep(0.001)
color(07) print("CD <Dirname>       CD <Drive>:        ") sleep(0.001)
color(7) print("SAVE <FileName> -c",false) color(6) print("     (Compress mode)") sleep(0.001)
color(7) print("CD ..  ",false) color(6) print("To go up a directory") sleep(0.001)
color(07) print("KEYMAP",false) color(6) print("  To change the controls config ") sleep(0.001)
color(07) print("PASTEBIN",false) color(6) print("  Print pastebin tool usage   ") sleep(0.001)
color(09) print("Use SAVE -c when uploading to pastebin") sleep(0.001)
color(06) print("") sleep(0.001)
color(07) print("Press ESC to toggle Editors mode      ") sleep(0.001)
color(07) print("") sleep(0.001)
color(12) print("Official Docs: http://liko-12.rtfd.io/" ) sleep(0.001)