name: liko-12
title: LIKO-12
summary: An open-source fantasy computer, powered by LÖVE
description: |
  LIKO-12 is a fantasy computer that you can use to make, play and share tiny retro-looking games and programs. It comes with a default, fully customizable, DOS-like operating system installed, called DiskOS.

  DiskOS provides an environment with basic command line programs and visual game editors.

  The created games and programs are saved as disk files that can be easily shared to friends or anyone else.
#icon: snap/gui/icon.png
license: MIT

adopt-info: liko-12
architectures:
- build-on: i386
- build-on: amd64
- build-on: armhf
- build-on: arm64
- build-on: ppc64el
base: core18
confinement: strict
grade: stable

parts:
  liko-12:
    after:
    - selective-checkout
    source: https://github.com/LIKO-12/LIKO-12.git
    source-depth: 800
    override-pull: |
      set -o nounset

      snapcraftctl pull

      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout

    plugin: dump
    organize:
      '*': LIKO-12/

  # Put stage-packages to separate part to avoid the organize rule in the liko-12 part
  liko-12-runtime-deps:
    plugin: nil
    stage-packages:
    - lua-sec

  love:
    plugin: nil
    stage-snaps:
    - love

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout
    prime:
    - -*

  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/

  icon:
    source: https://github.com/LIKO-12/Extras.git
    source-depth: 1
    plugin: dump
    stage:
    - Icon/icon-large.png

apps:
  liko-12:
    adapter: full
    command: bin/love $SNAP/LIKO-12
    command-chain:
    - bin/locales-launch
    - bin/love-launch
    - bin/liko-12-launch
    environment:
      # Workaround libpulsecommon library runtime dependency
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

plugs:
  # For snaps with a graphical user interface:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:

  # Storage access
  home:
  removable-media: # Non-A/C

  # Joystick access
  joystick:

  # Graphics rendering
  opengl:

  # Audio
  pulseaudio:

  # For inhibiting screensavor
  screen-inhibit-control:

  # Network access may be required by some games
  network:

layout:
  # Fix characters not in non-ASCII range not displayed in the window's
  # title bar
  /usr/share/X11/locale:
    bind: $SNAP/usr/share/X11/locale

  # Fix LUA_PATH, which is hardcoded at build time in LuaJIT
  /usr/share/lua/5.1:
    symlink: $SNAP/usr/share/lua/5.1

  # Fix LUA_CPATH, which is hardcoded at build time in LuaJIT
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lua/5.1:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lua/5.1

