name: Build & Deploy LIKO-12
on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install the dependencies
        run: yarn
      
      - name: Tag the build
        run: echo $GITHUB_REF_NAME > ./packages/app/res/version.txt

      - name: Transpile the project
        run: yarn build
      
      - name: Package the universal build
        run: ./scripts/universal.sh
      
      # ${VAR^^} substitutes the value and makes it uppercase.
      - name: Upload the universal build
        run: |
          cp './dist/out/liko_universal.love' "./dist/out/LIKO-12_${GITHUB_REF_NAME^^}_Universal.love"
          gh release upload $GITHUB_REF_NAME "./dist/out/LIKO-12_${GITHUB_REF_NAME^^}_Universal.love"